language: ruby
rvm:
- 2.3.0
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  deploy:
  provider: heroku
  app:
    master: pacific-island-40602